### PR TITLE
Upstream: Pull in changes from Hugo v0.74.2

### PR DESCRIPTION
**Pull request by felicianotech**

### CODE REVIEW

**Comment by mibragimchayev** [comment]
@felicianotech Did you mean to include docs/content/en/news/0.74.2-relnotes/index.md in this PR?

**Comment by felicianotech** [comment]
No, fixed.

**Comment by felicianotech** [comment]
Nice catch btw.

**Comment by felicianotech** [comment]
@mibragimchayev We may not need a lot of things but it's from upstream. I don't suggest we start nitpicking every change they do like this otherwise this becomes a lot of work.

**Pull request merged**
